#16 add dark theme button
Slacky300/REAL_TIME_EDIFY pull request #17
Opened 2024-09-08 19:23 UTC by a-mais

added button that changes the software theme and persists the chosen theme in the session
example of changes applied:
[changes.webm](https://github.com/user-attachments/assets/9c8d7bba-cbb8-4383-b147-56199de85318)

2024-09-08 20:28 UTC, Slacky300 requested changes
@a-mais just do the changes I mentioned, rest is good, Thanks for creating the pull request and contributing to this repo.

2024-09-08 20:28 UTC, Slacky300 commented on src/client/src/App.jsx
@a-mais please remove the comment from the `<PrivateRoutes/>`, since this will result in a vulnerability in the application, such that the users will be able to access the restricted pages without authenticating themselves.

2024-09-08 22:55 UTC, a-mais commented on src/client/src/App.jsx
I made a mend in the commit, I forgot about it

2024-09-09 08:21 UTC, Slacky300 approved these changes
@a-mais thanks for contibuting.

2024-09-09 08:21 UTC, merged